# Here we will install packages needed

install.packages("plyr")
install.packages("readxl")
install.packages("usmap")
install.packages("ggplot2")
install.packages("spdep")
install.packages("maptools")
install.packages("sp")
install.packages("lmtest")
install.packages("rgdal")
install.packages("spstat")
install.packages("car")
install.packages("spgwr")
install.packages("RColorBrewer")
install.packages("spatialreg")