# Lets load the packages

library(plyr)
library(readxl)
library(usmap)
library(ggplot2)
library(maptools)
library(sp)
library(spdep)
library(lmtest)
library(spatialreg)
library(tigris)
library(aod)
library(raster)
library(rgdal)
library(sf)
library(spData)
library(zoo)